Map keywordSet = {
  // Keywords
  'main': 'MAIN',
  // Reserved Words
  'action': 'ACTION',
  'bool': 'TYPE',
  'button': 'BUTTON',
  'column': 'COLUMN',
  'contents': 'CONTENTS',
  'double': 'TYPE',
  'else': 'ELSE',
  'false': 'BOOL',
  'field': 'FIELD',
  'for': 'FOR',
  'gui': 'GUI',
  'if': 'IF',
  'input': 'INPUT',
  'input_secure_storage': 'ISS',
  'int': 'TYPE',
  'label': 'LABEL',
  'print': 'PRINT',
  'purify_dev': 'PURIFY_DEV',
  'return': 'RETURN',
  'row': 'ROW',
  'string': 'TYPE',
  'text': 'TEXT',
  'true': 'BOOL',
  'value': 'VALUE',
  'void': 'VOID',
  'while': 'WHILE',
};
