Map keywordSet = {
  // Keywords
  'main': 'MAIN_KEYWORD',
  // Reserved Words
  'action': 'ACTION_KEYWORD',
  'array': 'ARRAY_KEYWORD',
  'bool': 'BOOL_KEYWORD',
  'button': 'BUTTON_KEYWORD',
  'column': 'COLUMN_KEYWORD',
  'contents': 'CONTENTS_KEYWORD',
  'double': 'DOUBLE_KEYWORD',
  'else': 'ELSE_KEYWORD',
  'false': 'FALSE_KEYWORD',
  'field': 'FIELD_KEYWORD',
  'for': 'FOR_KEYWORD',
  'gui': 'GUI_KEYWORD',
  'if': 'IF_KEYWORD',
  'input': 'INPUT_KEYWORD',
  'input_secure_storage': 'ISS_KEYWORD',
  'int': 'INT_KEYWORD',
  'label': 'LABEL_KEYWORD',
  'print': 'PRINT_KEYWORD',
  'purify_dev': 'PURIFY_DEV_KEYWORD',
  'return': 'RETURN_KEYWORD',
  'row': 'ROW_KEYWORD',
  'string': 'STRING_KEYWORD',
  'text': 'TEXT_KEYWORD',
  'true': 'TRUE_KEYWORD',
  'value': 'VALUE_KEYWORD',
  'void': 'VOID_KEYWORD',
  'while': 'WHILE_KEYWORD',
};
