Map keywordSet = {
  // Keywords
  'main': 'MAIN_KEYWORD',
  // Reserved Words
  'action': 'ACTION_RESWORD',
  'bool': 'BOOL_TYPE_RESWORD',
  'button': 'BUTTON_RESWORD',
  'column': 'COLUMN_RESWORD',
  'contents': 'CONTENTS_RESWORD',
  'double': 'DOUBLE_TYPE_RESWORD',
  'else': 'ELSE_RESWORD',
  'false': 'FALSE_RESWORD',
  'field': 'FIELD_RESWORD',
  'for': 'FOR_RESWORD',
  'gui': 'GUI_RESWORD',
  'if': 'IF_RESWORD',
  'input': 'INPUT_RESWORD',
  'input_secure_storage': 'ISS_RESWORD',
  'int': 'INT_TYPE_RESWORD',
  'label': 'LABEL_RESWORD',
  'print': 'PRINT_RESWORD',
  'purify_dev': 'PURIFY_DEV_RESWORD',
  'return': 'RETURN_RESWORD',
  'row': 'ROW_RESWORD',
  'string': 'STRING_TYPE_RESWORD',
  'text': 'TEXT_RESWORD',
  'true': 'TRUE_RESWORD',
  'value': 'VALUE_RESWORD',
  'void': 'VOID_RESWORD',
  'while': 'WHILE_RESWORD',
};
