Map operatorSet = {
  // Arithmetic
  '+': 'PLUS',
  '-': 'MINUS',
  '*': 'MUL_OP',
  '/': 'MUL_OP',
  '%': 'MUL_OP',
  '^': 'MUL_OP',
  '=': 'EQUAL',
  '+=': 'ASSIGN_OP',
  '-=': 'ASSIGN_OP',
  '*=': 'ASSIGN_OP',
  '/=': 'ASSIGN_OP',
  '%=': 'ASSIGN_OP',
  '^=': 'ASSIGN_OP',
  '++': 'INC_DEC_OP',
  '--': 'INC_DEC_OP',
  // Boolean
  '!': 'UNA_OP',
  '==': 'EQU_OP',
  '!=': 'EQU_OP',
  '<': 'REL_OP',
  '>': 'REL_OP',
  '<=': 'REL_OP',
  '>=': 'REL_OP',
  '&&': 'AND_OP',
  '||': 'OR_OP',
};
